config/routes.rb
Rails.application.routes.draw do

  resources :posts

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'


  #root 'admin/users#index'

  namespace :admin do
    resources :users
  end

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def admin?
     is_admin
  end
  has_many :posts
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :admin_required


  def index
     @users = User.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def admin_required
    if !current_user.admin?
      redirect_to "/"
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

   before_action :authenticate_user!

  def index
    @posts = current_user.posts
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path, notice: 'Update Success'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy
    redirect_to posts_path, alert: 'Post deleted'
  end

  private



  def post_params
    params.require(:post).permit(:title, :description)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
     flash[:notice] = "早安！你好！"
   end
 end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/users/index.html.erb
<table class="table table-bordered">

  <thead>
    <tr>
       <th class="col-md-6">  用户名  </th>
       <th class="col-md-6">  权限  </th>
   </tr>
  </thead>




  <tbody>

    <tr>
    <% @users.each do |user| %>
      <td>  <%= user.email %> </td>
      <td>  <%= user.is_admin %> </td>
    </tr>

     <% end %>
  </tbody>
</table>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2016 Eatgether
        <br>Design by team 5

    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Eatgether</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if !current_user %>
                  <li><%= link_to("注册", new_user_registration_path) %> </li>
                  <li><%= link_to("登入", new_user_session_path) %></li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                   <ul class="dropdown-menu">
                       <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eatgether 后台</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "common/navbar" %>
    <div class="row">
      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
          <li> <%= link_to("Users", admin_users_path) %> </li>
        </ul>
      </div>
      <div class="col-md-10">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eatgether</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= render "common/flashes" %>
            <%= yield %>
        </div>

        <%= render "common/footer" %>

    </body>
</html>

app/views/posts/edit.html.erb
<h2>修改约饭信息</h2>
<%= simple_form_for @post do |f| %>

  <div class="group">
    <%= f.input :title, label: '主题' %>
  </div>

  <div class="group">
    <%= f.input :description, label: '详细信息' %>
  </div>

  <%= f.submit "提交", class: "btn btn-default", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/posts/index.html.erb
<div class="col-md-12">
    <%= link_to("约饭", new_post_path(@post), class: "btn btn-danger pull-right") %>
</div>
<br>

<table class="table table-boldered">
    <thead>
        <tr>
            <th>约饭主题</th>
            <th>约饭内容</th>
            <th>控制面板</th>
        </tr>
    </thead>

    <tbody>
        <% @posts.each do |post| %>
        <tr>
            <td><%= link_to(post.title,post_path(post)) %></td>
            <td><%= post.description %></td>
            <td>
                <%= link_to("修改", edit_post_path(post), class: "btn btn-default") %>
                <%=link_to("删除", post_path(post), class: "btn btn-primary", method: :delete, data: { confirm: "Are you sure?" })%></td>
        </tr>
        <% end %>
    </tbody>
</table>
</div>
</div>

app/views/posts/new.html.erb
<h2>我要约饭</h2>
<%= simple_form_for @post do |f| %>

  <div class="group">
    <%= f.input :title, label: '主题' %>
  </div>

  <div class="group">
    <%= f.input :description, label: '详细信息' %>
  </div>

  <%= f.submit "提交", class: "btn btn-default", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/posts/show.html.erb
<table class="table table-boldered table-hover">
    <thead>
        <tr>
          <th>约饭主题</th>
          <th>约饭内容</th>
        </tr>
    </thead>

    <tbody>
           <tr>
            <td><%= @post.title %></td>
            <td><%= @post.description %></td>
          </tr>
    </tbody>
</table>

app/views/welcome/index.html.erb
<h1> Hello 约吗？ </h1>